language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "sudo sed -i '1i 127.0.0.1 test.box' /etc/hosts"
  - "sudo hostname test.box"
  - "sudo apt-add-repository -y ppa:sssd/updates "
  - "sudo apt-get update -q"
  - "DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq krb5-user krb5-kdc krb5-admin-server libkrb5-dev krb5-multidev"
  - "pip install --install-option='--no-cython-compile' cython"
  - "pip install -r test-requirements.txt"

script: ./.travis.sh
