from gssapi.raw.oids import OID
from gssapi.raw.named_tuples import DisplayNameResult

from typing import Optional

class Name:
    def __init__(self, cpy: Optional[Name] = None) -> None: ...

    # mypy is not smart enough to infer this from __init__
    def __new__(cls, cpy: Optional[Name] = None) -> Name: ...

    ...

def import_name(name: bytes, name_type: Optional[OID] = None) -> Name: ...

def display_name(name: Name, name_type: bool = True) -> DisplayNameResult: ...

def compare_name(name1: Optional[Name] = None,
                 name2: Optional[Name] = None) -> bool: ...

def export_name(name: Name) -> bytes: ...

def canonicalize_name(name: Name, mech: OID) -> Name: ...

def duplicate_name(name: Name) -> Name: ...

def release_name(name: Name) -> None: ...
